services:
  # Backend service
  - type: web
    name: qr-tracker-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/init_db.py
    startCommand: gunicorn backend.app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: backend/app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: qr-tracker-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: jholman@accelanalysis.com.com  # Change this to your admin email
      - key: ADMIN_PASSWORD
        value: Missions1!  # Change this to a secure password

  # Frontend service
  - type: web
    name: qr-tracker-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      VITE_API_URL=https://accelqr.onrender.com/api npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://accelqr.onrender.com  # This will be your backend URL

# Database configuration
databases:
  - name: qr-tracker-db
    databaseName: qrtracker
    user: qrtracker
    plan: free  # Use 'free' for development, 'starter' or higher for production
