services:
  # Backend service
  - type: web
    name: qr-tracker-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Initialize migrations if not exists
      if [ ! -d "migrations/versions" ]; then
        flask db init
        flask db migrate -m "Initial migration"
      fi
      # Always run upgrade
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: qr-tracker-db
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: qr-tracker-db
          property: connectionString

  # Frontend service
  - type: web
    name: qr-tracker-frontend
    env: node
    buildCommand: |
      npm install
      VITE_API_URL=https://accelqr.onrender.com/api npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://accelqr.onrender.com/api

# Database configuration
databases:
  - name: qr-tracker-db
    databaseName: qrtracker
    user: qrtracker
    plan: free  # Use 'free' for development, 'starter' or higher for production
