services:
  # Backend service
  - type: web
    name: qr-tracker-backend
    env: python
    buildCommand: |
      chmod +x ./build.sh
      ./build.sh
    startCommand: gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --timeout 600 --bind :$PORT backend.app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: backend/app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: qr-tracker-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: jholman@accelanalysis.com
      - key: ADMIN_PASSWORD
        value: Missions1!
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
    plan: free
    autoDeploy: true

  # Frontend service
  - type: web
    name: qr-tracker-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      VITE_API_URL=https://qr-tracker-backend.onrender.com/api npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://qr-tracker-backend.onrender.com/api  # Points to the backend API
    plan: free
    autoDeploy: true

# Database configuration
databases:
  - name: qr-tracker-db
    databaseName: qrtracker
    user: qrtracker
    plan: free  # Use 'free' for development, 'starter' or higher for production
