"""add folder column to qrcodes table

Revision ID: e7e66cab256c
Revises: 
Create Date: 2025-05-23 05:56:58.821861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e66cab256c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_qrcodes_folder'), ['folder'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qrcodes_folder'))
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
